// Rei, la perrita de la familia 🐶
// Tiene la carita negra, las cejas canela, las orejas peludas
// y el pelo dorado. Mira hacia la DERECHA, igual que el caballero.
// Cada letra es un píxel. Los colores nuevos están aquí abajo.
import { PALETA } from "./paleta.js";

export default {
  nombre: "rei",
  paleta: {
    ...PALETA,
    D: "#c9a577",   // dorado (el pelo de Rei)
    d: "#9c7a4e",   // dorado con sombra
    E: "#e6d3b0",   // crema (pecho y panza)
    T: "#e8c088",   // canela (cejas y cachetes)
    B: "#3b2a20",   // café oscuro (orejas peludas)
    b: "#22180f",   // oreja en sombra
    S: "#7d6e62",   // café grisáceo (la mancha del lomo)
    s: "#5a4e46",   // mancha del lomo en sombra
    m: "#a0602c",   // café de los ojos
    k: "#3a2c26",   // hocico negro (un poquito menos negro que la nariz)
    R: "#e8798a",   // rosado (lengua)
  },
  animaciones: {
    quieto: { velocidad: 2, repetir: true, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "................",
        ".......DDDDDD...",
        ".....BDDDDDDDDB.",
        "....BBDTTDDTTDDB",
        "...BBBTKKTTKKTDB",
        "...BBBKmWKKmWKTB",
        ".E.BbBKmmKKmmKTb",
        "EDEBbTTkkwKkkTTb",
        "EDDBbTTkkKKkkTTb",
        ".DDBb.TTkkkkTT.b",
        "..DBbSSSTEET...b",
        "..DSbsNAAAAN...b",
        ".DDSBSSNANDD...B",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "..DD.DD..DD.DD..",
        "..DD.DD..DD.DD..",
        "..DD.DD..EE.EE..",
        "..dd.dd..dd.dd..",
      ],
      [ // cuadro 2
        "................",
        "................",
        "................",
        "................",
        "................",
        ".......DDDDDD...",
        ".....BDDDDDDDDB.",
        "....BBDTTDDTTDDB",
        "...BBBTKKTTKKTDB",
        "E..BBBKmWKKmWKTB",
        "DE.BbBKmmKKmmKTb",
        "DDEBbTTkkwKkkTTb",
        ".DDBbTTkkKKkkTTb",
        "..DBbSTTkkkkTT.b",
        "..DBbssSTEET...b",
        ".DDSbSNAAAAN...b",
        ".DDDBDDNANDE...B",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "..DD.DD..DD.DD..",
        "..DD.DD..DD.DD..",
        "..DD.DD..EE.EE..",
        "..dd.dd..dd.dd..",
      ],
    ]},
    // Sentadita en la banca, con las patitas de atrás dobladas.
    sentado: { velocidad: 1, repetir: true, cuadros: [
      [ // cuadro 1: ojos abiertos
        "................",
        "................",
        "................",
        "................",
        ".......DDDDDD...",
        ".....BDDDDDDDDB.",
        "....BBDTTDDTTDDB",
        "...BBBTKKTTKKTDB",
        "...BBBKmWKKmWKTB",
        ".E.BbBKmmKKmmKTb",
        "EDEBbTTkkwKkkTTb",
        "EDDBbTTkkKKkkTTb",
        ".DDBb.TTkkkkTT.b",
        "..DBbSSSTEET...b",
        "..DSbsNAAAAN...b",
        ".DDSBSSNANDD...B",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        "ddDDDDDDDEEE....",
        "dDDDDDDDDEE.....",
        ".dDDDDDD.DE.....",
        ".dDDDDDD.DE.....",
        "..dDDDDd.DE.....",
        ".DDDDdd..dd.....",
      ],
      [ // cuadro 2: cierra los ojitos, ¡qué rico descansar!
        "................",
        "................",
        "................",
        "................",
        ".......DDDDDD...",
        ".....BDDDDDDDDB.",
        "....BBDTTDDTTDDB",
        "...BBBTKKTTKKTDB",
        "...BBBKKKKKKKKTB",
        ".E.BbBKkkKKkkKTb",
        "EDEBbTTkkwKkkTTb",
        "EDDBbTTkkKKkkTTb",
        ".DDBb.TTkkkkTT.b",
        "..DBbSSSTEET...b",
        "..DSbsNAAAAN...b",
        ".DDSBSSNANDD...B",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        "ddDDDDDDDEEE....",
        "dDDDDDDDDEE.....",
        ".dDDDDDD.DE.....",
        ".dDDDDDD.DE.....",
        "..dDDDDd.DE.....",
        ".DDDDdd..dd.....",
      ],
    ]},
    correr: { velocidad: 10, repetir: true, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "................",
        "................",
        ".......DDDDDD...",
        ".....BDDDDDDDDB.",
        "....BBDTTDDTTDDB",
        "...BBBTKKTTKKTDB",
        "...BBBKmWKKmWKTB",
        "...BbBKmmKKmmKTb",
        "...BbTTkkwKkkTTb",
        "EE.BbTTkkKKkkTTb",
        "EDDBbSTTkkkkTT.b",
        ".DDBbssSTEET...b",
        ".DDSbSNAAAAN...b",
        ".DDDBDDNANDE...B",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "..DDDD....DDDD..",
        ".DD..DD..DD..DD.",
        ".D....D..E....E.",
        "dd....dddd....dd",
      ],
      [ // cuadro 2
        "................",
        "................",
        "................",
        "...B...DDDDDD...",
        "...BB.DDDDDDDD.B",
        "...BBBDTTDDTTDDB",
        "...BbBTKKTTKKTDb",
        "...BbBKmWKKmWKTb",
        ".E..bBKmmKKmmKTb",
        "EDE.BTTkkwKkkTTB",
        "EDD..TTkkKKkkTT.",
        ".DD...TTkkkkTT..",
        "..DSSSSSTEET....",
        "..DSSsNAAAAN....",
        ".DDSSSSNANDD....",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "................",
        "...DDD....DDD...",
        "...DDD....EEE...",
        "...DD.....EE....",
        "...dd.....dd....",
      ],
      [ // cuadro 3
        "................",
        "................",
        "................",
        "................",
        "................",
        ".......DDDDDD...",
        ".....BDDDDDDDDB.",
        "....BBDTTDDTTDDB",
        "...BBBTKKTTKKTDB",
        "E..BBBKmWKKmWKTB",
        "DE.BbBKmmKKmmKTb",
        "DDEBbTTkkwKkkTTb",
        ".DDBbTTkkKKkkTTb",
        "..DBbSTTkkkkTT.b",
        "..DBbssSTEET...b",
        ".DDSbSNAAAAN...b",
        ".DDDBDDNANDE...B",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "..DDDD....DDDD..",
        ".DD..DD..DD..DD.",
        ".D....D..E....E.",
        "dd....dddd....dd",
      ],
      [ // cuadro 4
        "................",
        "................",
        "................",
        "...B...DDDDDD...",
        "...BB.DDDDDDDD.B",
        "...BBBDTTDDTTDDB",
        "...BbBTKKTTKKTDb",
        "...BbBKmWKKmWKTb",
        "....bBKmmKKmmKTb",
        "....BTTkkwKkkTTB",
        ".....TTkkKKkkTT.",
        "EE....TTkkkkTT..",
        "EDDSSSSSTEET....",
        ".DDSSsNAAAAN....",
        ".DDSSSSNANDD....",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "................",
        "...DDD....DDD...",
        "...DDD....EEE...",
        "...DD.....EE....",
        "...dd.....dd....",
      ],
    ]},
    saltar: { velocidad: 1, repetir: false, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "................",
        "...B...DDDDDD...",
        "...BB.DDDDDDDD.B",
        "...BBBDTTDDTTDDB",
        "...BbBTKKTTKKTDb",
        "...BbBKmWKKmWKTb",
        "....bBKmmKKmmKTb",
        "....BTTkkwKkkTTB",
        ".....TTkkKKkkTT.",
        "EE....TTkkkkTT..",
        "EDDSSSSSTEET....",
        ".DDSSsNAAAAN....",
        ".DDSSSSNANDD....",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        ".DDD......DDDD..",
        "dd.........EEdd.",
        "................",
        "................",
      ],
    ]},
    caer: { velocidad: 1, repetir: false, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "...B...DDDDDD...",
        "...BB.DDDDDDDD.B",
        "...BBBDTTDDTTDDB",
        "...BbBTKKTTKKTDb",
        "...BbBKmWKKmWKTb",
        ".E..bBKmmKKmmKTb",
        "EDE.BTTkkwKkkTTB",
        "EDD..TTkkKKkkTT.",
        ".DD...TTkkkkTT..",
        "..D.....TEET....",
        "...SSSNAAAAN....",
        "..DSSssNAND.....",
        ".DDSSSSSSDDD....",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "...DD.DD..DD.DD.",
        "...DD.DD..EE.EE.",
        "...dd.dd..dd.dd.",
        "................",
      ],
    ]},
    atacar: { velocidad: 12, repetir: false, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "................",
        "......DDDDDD....",
        "....BDDDDDDDDB..",
        "...BBDTTDDTTDDB.",
        "..BBBTKKTTKKTDBB",
        "..BBBKmWKKmWKTBB",
        "E.BbBKmmKKmmKTbB",
        "DEBbTTkkwKkkTTbB",
        "DDBbTTkkKKkkTTbB",
        "DDBb.TTkkkkTT.bB",
        ".DBbSSSTEET...bB",
        ".DSbsNAAAAN...b.",
        "DDSBSSNANDD...B.",
        "DDDDDDDDDDE.....",
        "dDDDDDDDDEE.....",
        "dDDDDDDDEEE.....",
        ".dEEEEEEEE......",
        ".DD.DD..DD.DD...",
        ".DD.DD..DD.DD...",
        ".DD.DD..EE.EE...",
        ".dd.dd..dd.dd...",
      ],
      [ // cuadro 2
        "................",
        "................",
        "................",
        "................",
        "........DDDDDD..",
        "......BDDDDDDDDB",
        ".....BBDTTDDTTDD",
        "....BBBTKKTTKKTD",
        "....BBBKmWKKmWKT",
        "E...BbBKmmKKmmKT",
        "DE..BbTTkkwKkkTT",
        "DDE.BbTTkkKKkkTT",
        ".DD.Bb.TkWkWkWk.",
        "..DSBbSTkRRRRRk.",
        "..DSSbsNAAAANW..",
        ".DDSSBSSNAND....",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "..DD.DD..DD.EEdd",
        "..DD.DD..DD.....",
        "..DD.DD..EE.....",
        "..dd.dd..dd.....",
      ],
    ]},
    dash: { velocidad: 1, repetir: false, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "........DDDDDD..",
        ".......DDDDDDDD.",
        ".BBBB.DDTTDDTTDD",
        "wwBbbBBTKKTTKKTD",
        "..BBbbBKmWKKmWKT",
        "....BBTKmmKKmmKT",
        "www...TTkkwKkkTT",
        "......TTkkKKkkTT",
        ".......TTkkkkTT.",
        "DD.SSSSSSTEET...",
        "DDSSSssNAAAAN...",
        "dDDSSSSSNANDE...",
        "dDDDDDDDDDEEE...",
        ".ddEEEEEEEEE....",
        "dDDD......DDEEdd",
        "dd..............",
        "................",
        "................",
      ],
    ]},
    herido: { velocidad: 1, repetir: false, cuadros: [
      [ // cuadro 1
        "................",
        "................",
        "................",
        "................",
        "...B...DDDDDD...",
        "...BB.DDDDDDDD.B",
        "...BBBDTTDDTTDDB",
        "...BbBTKKTTKKTDb",
        "...BbBmKKKKKKmTb",
        "E...bBKmmKKmmKTb",
        "DE..BTTkkwKkkTTB",
        "DDE..TTkkKKkkTT.",
        ".DD...TTkRRkTT..",
        "..DSSSSSTEET....",
        "..DSSsNAAAAN....",
        ".DDSSSSNANDD....",
        ".DDDDDDDDDDE....",
        ".dDDDDDDDDEE....",
        ".dDDDDDDDEEE....",
        "..dEEEEEEEE.....",
        "..DDDD....DDDD..",
        ".DD..DD..DD..DD.",
        ".D....D..E....E.",
        "dd....dddd....dd",
      ],
    ]},
  },
};
